	.align 2
DirectSoundWaveData_sc88_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88_organ2::
	.incbin "sound/direct_sound_samples/sc88_organ2.bin"

	.align 2
DirectSoundWaveData_sc88_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88_fretless_bass.bin"

	.align 2
DirectSoundWaveData_jv1080_slap_bass::
	.incbin "sound/direct_sound_samples/jv1080_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88_synth_bass::
	.incbin "sound/direct_sound_samples/sc88_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88_timpani::
	.incbin "sound/direct_sound_samples/sc88_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_electric_guitar::
	.incbin "sound/direct_sound_samples/unused_electric_guitar.bin"

	.align 2
DirectSoundWaveData_unused_sc88_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_unknown_wood_block_low::
	.incbin "sound/direct_sound_samples/unknown_wood_block_low.bin"

	.align 2
DirectSoundWaveData_unknown_wood_block_high::
	.incbin "sound/direct_sound_samples/unknown_wood_block_high.bin"

	.align 2
DirectSoundWaveData_sc88_standard_kick::
	.incbin "sound/direct_sound_samples/sc88_standard_kick.bin"

	.align 2
DirectSoundWaveData_sc88_standard3_snare::
	.incbin "sound/direct_sound_samples/sc88_standard3_snare.bin"

	.align 2
DirectSoundWaveData_sc88_standard_hand_clap::
	.incbin "sound/direct_sound_samples/sc88_standard_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unknown_tom::
	.incbin "sound/direct_sound_samples/unknown_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_unknown_tambourine::
	.incbin "sound/direct_sound_samples/unknown_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88_bongo::
	.incbin "sound/direct_sound_samples/sc88_bongo.bin"

	.align 2
DirectSoundWaveData_sc88_bongo_low::
	.incbin "sound/direct_sound_samples/sc88_bongo_low.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_unknown_cowbell::
	.incbin "sound/direct_sound_samples/unknown_cowbell.bin"

	.align 2
DirectSoundWaveData_unknown_djembe::
	.incbin "sound/direct_sound_samples/unknown_djembe.bin"

	.align 2
DirectSoundWaveData_unknown_anvil_high::
	.incbin "sound/direct_sound_samples/unknown_anvil_high.bin"

	.align 2
DirectSoundWaveData_sc88_standard_bells::
	.incbin "sound/direct_sound_samples/sc88_standard_bells.bin"

	.align 2
DirectSoundWaveData_unknown_anvil_low::
	.incbin "sound/direct_sound_samples/unknown_anvil_low.bin"

	.align 2
DirectSoundWaveData_unknown_ethnic_drum::
	.incbin "sound/direct_sound_samples/unknown_ethnic_drum.bin"

	.align 2
DirectSoundWaveData_unknown_tsuzumi::
	.incbin "sound/direct_sound_samples/unknown_tsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_48::
	.incbin "sound/direct_sound_samples/sc88_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_60::
	.incbin "sound/direct_sound_samples/sc88_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_72::
	.incbin "sound/direct_sound_samples/sc88_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_84::
	.incbin "sound/direct_sound_samples/sc88_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88_trumpet_84.bin"

	.align 2
DirectSoundWaveData_unknown_trombone_39::
	.incbin "sound/direct_sound_samples/unknown_trombone_39.bin"

	.align 2
DirectSoundWaveData_unknown_trombone_51::
	.incbin "sound/direct_sound_samples/unknown_trombone_51.bin"

	.align 2
DirectSoundWaveData_sc88_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88_flute::
	.incbin "sound/direct_sound_samples/sc88_flute.bin"

	.align 2
DirectSoundWaveData_sc88_pick_bass::
	.incbin "sound/direct_sound_samples/sc88_pick_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_unknown_church_organ::
	.incbin "sound/direct_sound_samples/unknown_church_organ.bin"

	.align 2
DirectSoundWaveData_emu_ii_pipe_organ::
	.incbin "sound/direct_sound_samples/emu_ii_pipe_organ.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88_square_wave::
	.incbin "sound/direct_sound_samples/sc88_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88_wind::
	.incbin "sound/direct_sound_samples/sc88_wind.bin"

	.align 2
DirectSoundWaveData_sc88_bubbles::
	.incbin "sound/direct_sound_samples/sc88_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_unused_acid_bass::
	.incbin "sound/direct_sound_samples/unused_acid_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_unknown_polysynth::
	.incbin "sound/direct_sound_samples/unknown_polysynth.bin"

	.align 2
DirectSoundWaveData_sc88_harp::
	.incbin "sound/direct_sound_samples/sc88_harp.bin"

	.align 2
DirectSoundWaveData_sc88_xylophone::
	.incbin "sound/direct_sound_samples/sc88_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88_accordion::
	.incbin "sound/direct_sound_samples/sc88_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cries/bulbasaur.bin"

	.align 2
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cries/ivysaur.bin"

	.align 2
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cries/venusaur.bin"

	.align 2
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cries/charmander.bin"

	.align 2
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cries/charmeleon.bin"

	.align 2
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cries/charizard.bin"

	.align 2
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cries/squirtle.bin"

	.align 2
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cries/wartortle.bin"

	.align 2
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cries/blastoise.bin"

	.align 2
Cry_Snivy::
	.incbin "sound/direct_sound_samples/cries/snivy.bin"

	.align 2
Cry_Servine::
	.incbin "sound/direct_sound_samples/cries/servine.bin"

	.align 2
Cry_Serperior::
	.incbin "sound/direct_sound_samples/cries/serperior.bin"

	.align 2
Cry_Weedle::
	.incbin "sound/direct_sound_samples/cries/weedle.bin"

	.align 2
Cry_Kakuna::
	.incbin "sound/direct_sound_samples/cries/kakuna.bin"

	.align 2
Cry_Beedrill::
	.incbin "sound/direct_sound_samples/cries/beedrill.bin"

	.align 2
Cry_Pidgey::
	.incbin "sound/direct_sound_samples/cries/pidgey.bin"

	.align 2
Cry_Pidgeotto::
	.incbin "sound/direct_sound_samples/cries/pidgeotto.bin"

	.align 2
Cry_Pidgeot::
	.incbin "sound/direct_sound_samples/cries/pidgeot.bin"

	.align 2
Cry_Alolan_Vulpix::
	.incbin "sound/direct_sound_samples/cries/alolan_vulpix.bin"

	.align 2
Cry_Alolan_Ninetales::
	.incbin "sound/direct_sound_samples/cries/alolan_ninetales.bin"

	.align 2
Cry_Noibat::
	.incbin "sound/direct_sound_samples/cries/noibat.bin"

	.align 2
Cry_Noivern::
	.incbin "sound/direct_sound_samples/cries/noivern.bin"

	.align 2
Cry_Ekans::
	.incbin "sound/direct_sound_samples/cries/ekans.bin"

	.align 2
Cry_Arbok::
	.incbin "sound/direct_sound_samples/cries/arbok.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cries/pikachu.bin"

	.align 2
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cries/raichu.bin"

	.align 2
Cry_Sandshrew::
	.incbin "sound/direct_sound_samples/cries/sandshrew.bin"

	.align 2
Cry_Sandslash::
	.incbin "sound/direct_sound_samples/cries/sandslash.bin"

	.align 2
Cry_NidoranF::
	.incbin "sound/direct_sound_samples/cries/nidoran_f.bin"

	.align 2
Cry_Nidorina::
	.incbin "sound/direct_sound_samples/cries/nidorina.bin"

	.align 2
Cry_Nidoqueen::
	.incbin "sound/direct_sound_samples/cries/nidoqueen.bin"

	.align 2
Cry_NidoranM::
	.incbin "sound/direct_sound_samples/cries/nidoran_m.bin"

	.align 2
Cry_Nidorino::
	.incbin "sound/direct_sound_samples/cries/nidorino.bin"

	.align 2
Cry_Nidoking::
	.incbin "sound/direct_sound_samples/cries/nidoking.bin"

	.align 2
Cry_Clefairy::
	.incbin "sound/direct_sound_samples/cries/clefairy.bin"

	.align 2
Cry_Clefable::
	.incbin "sound/direct_sound_samples/cries/clefable.bin"

	.align 2
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cries/vulpix.bin"

	.align 2
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cries/ninetales.bin"

	.align 2
Cry_Froakie::
	.incbin "sound/direct_sound_samples/cries/froakie.bin"

	.align 2
Cry_Frogadier::
	.incbin "sound/direct_sound_samples/cries/frogadier.bin"

	.align 2
Cry_Greninja::
	.incbin "sound/direct_sound_samples/cries/greninja.bin"

	.align 2
Cry_Bonded_Greninja::
	.incbin "sound/direct_sound_samples/cries/durant.bin"

	.align 2
Cry_Rowlet::
	.incbin "sound/direct_sound_samples/cries/rowlet.bin"

	.align 2
Cry_Dartrix::
	.incbin "sound/direct_sound_samples/cries/dartrix.bin"

	.align 2
Cry_Decidueye::
	.incbin "sound/direct_sound_samples/cries/decidueye.bin"

	.align 2
Cry_Bidoof::
	.incbin "sound/direct_sound_samples/cries/bidoof.bin"

	.align 2
Cry_Bibarel::
	.incbin "sound/direct_sound_samples/cries/bibarel.bin"

	.align 2
Cry_Venonat::
	.incbin "sound/direct_sound_samples/cries/venonat.bin"

	.align 2
Cry_Venomoth::
	.incbin "sound/direct_sound_samples/cries/venomoth.bin"

	.align 2
Cry_Karrablast::
	.incbin "sound/direct_sound_samples/cries/karrablast.bin"

	.align 2
Cry_Escavalier::
	.incbin "sound/direct_sound_samples/cries/escavalier.bin"

	.align 2
Cry_Tyrunt::
	.incbin "sound/direct_sound_samples/cries/tyrunt.bin"

	.align 2
Cry_Tyrantrum::
	.incbin "sound/direct_sound_samples/cries/tyrantrum.bin"

	.align 2
Cry_Combee::
	.incbin "sound/direct_sound_samples/cries/combee.bin"

	.align 2
Cry_Vespiquen::
	.incbin "sound/direct_sound_samples/cries/vespiqueen.bin"

	.align 2
Cry_Purrloin::
	.incbin "sound/direct_sound_samples/cries/purrloin.bin"

	.align 2
Cry_Liepard::
	.incbin "sound/direct_sound_samples/cries/liepard.bin"

	.align 2
Cry_Growlithe::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Arcanine::
	.incbin "sound/direct_sound_samples/cries/arcanine.bin"

	.align 2
Cry_Pidove::
	.incbin "sound/direct_sound_samples/cries/pidove.bin"

	.align 2
Cry_Tranquill::
	.incbin "sound/direct_sound_samples/cries/tranquill.bin"

	.align 2
Cry_Unfezant::
	.incbin "sound/direct_sound_samples/cries/unfezant.bin"

	.align 2
Cry_Abra::
	.incbin "sound/direct_sound_samples/cries/abra.bin"

	.align 2
Cry_Kadabra::
	.incbin "sound/direct_sound_samples/cries/kadabra.bin"

	.align 2
Cry_Alakazam::
	.incbin "sound/direct_sound_samples/cries/alakazam.bin"

	.align 2
Cry_Scatterbug::
	.incbin "sound/direct_sound_samples/cries/scatterbug.bin"

	.align 2
Cry_Spewpa::
	.incbin "sound/direct_sound_samples/cries/spewpa.bin"

	.align 2
Cry_Vivillon::
	.incbin "sound/direct_sound_samples/cries/vivillon.bin"

	.align 2
Cry_Venipede::
	.incbin "sound/direct_sound_samples/cries/venipede.bin"

	.align 2
Cry_Whirlipede::
	.incbin "sound/direct_sound_samples/cries/whirlipede.bin"

	.align 2
Cry_Scolipede::
	.incbin "sound/direct_sound_samples/cries/scolipede.bin"

	.align 2
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cries/tentacool.bin"

	.align 2
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cries/tentacruel.bin"

	.align 2
Cry_Espurr::
	.incbin "sound/direct_sound_samples/cries/espurr.bin"

	.align 2
Cry_MeowsticM::
	.incbin "sound/direct_sound_samples/cries/meowstic.bin"

	.align 2
Cry_MeowsticF::
	.incbin "sound/direct_sound_samples/cries/meowstic.bin"

	.align 2
Cry_Ponyta::
	.incbin "sound/direct_sound_samples/cries/ponyta.bin"

	.align 2
Cry_Rapidash::
	.incbin "sound/direct_sound_samples/cries/rapidash.bin"

	.align 2
Cry_Vullaby::
	.incbin "sound/direct_sound_samples/cries/vullaby.bin"

	.align 2
Cry_Mandibuzz::
	.incbin "sound/direct_sound_samples/cries/mandibuzz.bin"

	.align 2
Cry_Magnemite::
	.incbin "sound/direct_sound_samples/cries/magnemite.bin"

	.align 2
Cry_Magneton::
	.incbin "sound/direct_sound_samples/cries/magneton.bin"

	.align 2
Cry_Magnezone::
	.incbin "sound/direct_sound_samples/cries/magnezone.bin"

	.align 2
Cry_Rotom::
	.incbin "sound/direct_sound_samples/cries/rotom.bin"

	.align 2
Cry_Lillipup::
	.incbin "sound/direct_sound_samples/cries/lillipup.bin"

	.align 2
Cry_Herdier::
	.incbin "sound/direct_sound_samples/cries/herdier.bin"

	.align 2
Cry_Stoutland::
	.incbin "sound/direct_sound_samples/cries/stoutland.bin"

	.align 2
Cry_Mudbray::
	.incbin "sound/direct_sound_samples/cries/mudbray.bin"

	.align 2
Cry_Mudsdale::
	.incbin "sound/direct_sound_samples/cries/mudsdale.bin"

	.align 2
Cry_Ducklett::
	.incbin "sound/direct_sound_samples/cries/ducklett.bin"

	.align 2
Cry_Swanna::
	.incbin "sound/direct_sound_samples/cries/swanna.bin"

	.align 2
Cry_Gastly::
	.incbin "sound/direct_sound_samples/cries/gastly.bin"

	.align 2
Cry_Haunter::
	.incbin "sound/direct_sound_samples/cries/haunter.bin"

	.align 2
Cry_Gengar::
	.incbin "sound/direct_sound_samples/cries/gengar.bin"

	.align 2
Cry_Onix::
	.incbin "sound/direct_sound_samples/cries/onix.bin"

	.align 2
Cry_Rufflet::
	.incbin "sound/direct_sound_samples/cries/rufflet.bin"

	.align 2
Cry_Braviary::
	.incbin "sound/direct_sound_samples/cries/braviary.bin"

	.align 2
Cry_Krabby::
	.incbin "sound/direct_sound_samples/cries/krabby.bin"

	.align 2
Cry_Kingler::
	.incbin "sound/direct_sound_samples/cries/kingler.bin"

	.align 2
Cry_Scraggy::
	.incbin "sound/direct_sound_samples/cries/scraggy.bin"

	.align 2
Cry_Scrafty::
	.incbin "sound/direct_sound_samples/cries/scrafty.bin"

	.align 2
Cry_Cubchoo::
	.incbin "sound/direct_sound_samples/cries/cubchoo.bin"

	.align 2
Cry_Beartic::
	.incbin "sound/direct_sound_samples/cries/beartic.bin"

	.align 2
Cry_Cubone::
	.incbin "sound/direct_sound_samples/cries/cubone.bin"

	.align 2
Cry_Marowak::
	.incbin "sound/direct_sound_samples/cries/marowak.bin"

	.align 2
Cry_Hitmonlee::
	.incbin "sound/direct_sound_samples/cries/hitmonlee.bin"

	.align 2
Cry_Hitmonchan::
	.incbin "sound/direct_sound_samples/cries/hitmonchan.bin"

	.align 2
Cry_Bunnelby::
	.incbin "sound/direct_sound_samples/cries/bunnelby.bin"

	.align 2
Cry_Diggersby::
	.incbin "sound/direct_sound_samples/cries/diggersby.bin"

	.align 2
Cry_Bonded_Beartic::
	.incbin "sound/direct_sound_samples/cries/bonded_beartic.bin"

	.align 2
Cry_Rhyhorn::
	.incbin "sound/direct_sound_samples/cries/rhyhorn.bin"

	.align 2
Cry_Rhydon::
	.incbin "sound/direct_sound_samples/cries/rhydon.bin"

	.align 2
Cry_Chansey::
	.incbin "sound/direct_sound_samples/cries/rhyperior.bin"

	.align 2
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cries/tangela.bin"

	.align 2
Cry_Tangrowth::
	.incbin "sound/direct_sound_samples/cries/tangrowth.bin"

	.align 2
Cry_Buizel::
	.incbin "sound/direct_sound_samples/cries/buizel.bin"

	.align 2
Cry_Floatzel::
	.incbin "sound/direct_sound_samples/cries/floatzel.bin"

	.align 2
Cry_Drillbur::
	.incbin "sound/direct_sound_samples/cries/drillbur.bin"

	.align 2
Cry_Excadrill::
	.incbin "sound/direct_sound_samples/cries/excadrill.bin"

	.align 2
Cry_Staryu::
	.incbin "sound/direct_sound_samples/cries/staryu.bin"

	.align 2
Cry_Starmie::
	.incbin "sound/direct_sound_samples/cries/starmie.bin"

	.align 2
Cry_MrMime::
	.incbin "sound/direct_sound_samples/cries/bonded_flygon.bin"

	.align 2
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cries/scyther.bin"

	.align 2
Cry_Larvesta::
	.incbin "sound/direct_sound_samples/cries/larvesta.bin"

	.align 2
Cry_Volcarona::
	.incbin "sound/direct_sound_samples/cries/volcarona.bin"

	.align 2
Cry_Foongus::
	.incbin "sound/direct_sound_samples/cries/foonguss.bin"

	.align 2
Cry_Pinsir::
	.incbin "sound/direct_sound_samples/cries/pinsir.bin"

	.align 2
Cry_Amoonguss::
	.incbin "sound/direct_sound_samples/cries/amoonguss.bin"

	.align 2
Cry_Magikarp::
	.incbin "sound/direct_sound_samples/cries/magikarp.bin"

	.align 2
Cry_Gyarados::
	.incbin "sound/direct_sound_samples/cries/gyarados.bin"

	.align 2
Cry_Lapras::
	.incbin "sound/direct_sound_samples/cries/lapras.bin"

	.align 2
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cries/ditto.bin"

	.align 2
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cries/eevee.bin"

	.align 2
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cries/vaporeon.bin"

	.align 2
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cries/jolteon.bin"

	.align 2
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cries/flareon.bin"

	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cries/porygon.bin"

	.align 2
Cry_Skorupi::
	.incbin "sound/direct_sound_samples/cries/skorupi.bin"

	.align 2
Cry_Drapion::
	.incbin "sound/direct_sound_samples/cries/drapion.bin"

	.align 2
Cry_Skrelp::
	.incbin "sound/direct_sound_samples/cries/skrelp.bin"

	.align 2
Cry_Dragalge::
	.incbin "sound/direct_sound_samples/cries/dragalge.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cries/aerodactyl.bin"

	.align 2
Cry_Snorlax::
	.incbin "sound/direct_sound_samples/cries/snorlax.bin"

	.align 2
Cry_Bonded_Kyogre::
	.incbin "sound/direct_sound_samples/cries/bonded_kyogre.bin"

	.align 2
Cry_Bonded_Groudon::
	.incbin "sound/direct_sound_samples/cries/bonded_groudon.bin"

	.align 2
Cry_Bonded_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/bonded_rayquaza.bin"

	.align 2
Cry_Goomy::
	.incbin "sound/direct_sound_samples/cries/goomy.bin"

	.align 2
Cry_Sliggoo::
	.incbin "sound/direct_sound_samples/cries/sliggoo.bin"

	.align 2
Cry_Goodra::
	.incbin "sound/direct_sound_samples/cries/goodra.bin"

	.align 2
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cries/mewtwo.bin"

	.align 2
Cry_Mew::
	.incbin "sound/direct_sound_samples/cries/mew.bin"

	.align 2
Cry_Snover::
	.incbin "sound/direct_sound_samples/cries/snover.bin"

	.align 2
Cry_Abomasnow::
	.incbin "sound/direct_sound_samples/cries/abomasnow.bin"

	.align 2
Cry_Abomacier::
	.incbin "sound/direct_sound_samples/cries/abomacier.bin"

	.align 2
Cry_Cyndaquil::
	.incbin "sound/direct_sound_samples/cries/cyndaquil.bin"

	.align 2
Cry_Quilava::
	.incbin "sound/direct_sound_samples/cries/quilava.bin"

	.align 2
Cry_Typhlosion::
	.incbin "sound/direct_sound_samples/cries/typhlosion.bin"

	.align 2
Cry_Basculin::
	.incbin "sound/direct_sound_samples/cries/basculin.bin"

	.align 2
Cry_Wimpod::
	.incbin "sound/direct_sound_samples/cries/wimpod.bin"

	.align 2
Cry_Golisopod::
	.incbin "sound/direct_sound_samples/cries/golisopod.bin"

	.align 2
Cry_Sentret::
	.incbin "sound/direct_sound_samples/cries/sentret.bin"

	.align 2
Cry_Furret::
	.incbin "sound/direct_sound_samples/cries/furret.bin"

	.align 2
Cry_Ferroseed::
	.incbin "sound/direct_sound_samples/cries/ferroseed.bin"

	.align 2
Cry_Ferrothorn::
	.incbin "sound/direct_sound_samples/cries/ferrothorn.bin"

	.align 2
Cry_Clauncher::
	.incbin "sound/direct_sound_samples/cries/clauncher.bin"

	.align 2
Cry_Clawitzer::
	.incbin "sound/direct_sound_samples/cries/clawitzer.bin"

	.align 2
Cry_Spinarak::
	.incbin "sound/direct_sound_samples/cries/spinarak.bin"

	.align 2
Cry_Ariados::
	.incbin "sound/direct_sound_samples/cries/ariados.bin"

	.align 2
Cry_Mimikyu::
	.incbin "sound/direct_sound_samples/cries/mimikyu.bin"

	.align 2
Cry_Chinchou::
	.incbin "sound/direct_sound_samples/cries/chinchou.bin"

	.align 2
Cry_Lanturn::
	.incbin "sound/direct_sound_samples/cries/lanturn.bin"

	.align 2
Cry_Sewaddle::
	.incbin "sound/direct_sound_samples/cries/sewaddle.bin"

	.align 2
Cry_Swadloon::
	.incbin "sound/direct_sound_samples/cries/swadloon.bin"

	.align 2
Cry_Leavanny::
	.incbin "sound/direct_sound_samples/cries/leavanny.bin"

	.align 2
Cry_Togepi::
	.incbin "sound/direct_sound_samples/cries/togepi.bin"

	.align 2
Cry_Togetic::
	.incbin "sound/direct_sound_samples/cries/togetic.bin"

	.align 2
Cry_Togekiss::
	.incbin "sound/direct_sound_samples/cries/togekiss.bin"

	.align 2
Cry_Phantump::
	.incbin "sound/direct_sound_samples/cries/phantump.bin"

	.align 2
Cry_Mareep::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Flaaffy::
	.incbin "sound/direct_sound_samples/cries/flaaffy.bin"

	.align 2
Cry_Ampharos::
	.incbin "sound/direct_sound_samples/cries/ampharos.bin"

	.align 2
Cry_Trevenant::
	.incbin "sound/direct_sound_samples/cries/trevenant.bin"

	.align 2
Cry_Marill::
	.incbin "sound/direct_sound_samples/cries/marill.bin"

	.align 2
Cry_Azumarill::
	.incbin "sound/direct_sound_samples/cries/azumarill.bin"

	.align 2
Cry_Gible::
	.incbin "sound/direct_sound_samples/cries/gible.bin"

	.align 2
Cry_Gabite::
	.incbin "sound/direct_sound_samples/cries/gabite.bin"

	.align 2
Cry_Garchomp::
	.incbin "sound/direct_sound_samples/cries/garchomp.bin"

	.align 2
Cry_Honedge::
	.incbin "sound/direct_sound_samples/cries/honedge.bin"

	.align 2
Cry_Doublade::
	.incbin "sound/direct_sound_samples/cries/doublade.bin"

	.align 2
Cry_Aegislash::
	.incbin "sound/direct_sound_samples/cries/aegislash.bin"

	.align 2
Cry_Scimiteye::
	.incbin "sound/direct_sound_samples/cries/scimiteye.bin"

	.align 2
Cry_Jawguile::
	.incbin "sound/direct_sound_samples/cries/jawguile.bin"

	.align 2
Cry_Bonded_Raichu::
	.incbin "sound/direct_sound_samples/cries/bonded_raichu.bin"

	.align 2
Cry_Wooper::
	.incbin "sound/direct_sound_samples/cries/wooper.bin"

	.align 2
Cry_Quagsire::
	.incbin "sound/direct_sound_samples/cries/quagsire.bin"

	.align 2
Cry_Espeon::
	.incbin "sound/direct_sound_samples/cries/espeon.bin"

	.align 2
Cry_Umbreon::
	.incbin "sound/direct_sound_samples/cries/umbreon.bin"

	.align 2
Cry_Leafeon::
	.incbin "sound/direct_sound_samples/cries/leafeon.bin"

	.align 2
Cry_Glaceon::
	.incbin "sound/direct_sound_samples/cries/glaceon.bin"

	.align 2
Cry_Sylveon::
	.incbin "sound/direct_sound_samples/cries/sylveon.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cries/flabebe.bin"

	.align 2
Cry_Floette::
	.incbin "sound/direct_sound_samples/cries/floette.bin"

	.align 2
Cry_Florges::
	.incbin "sound/direct_sound_samples/cries/florges.bin"

	.align 2
Cry_Joltik::
	.incbin "sound/direct_sound_samples/cries/joltik.bin"

	.align 2
Cry_Galvantula::
	.incbin "sound/direct_sound_samples/cries/galvantula.bin"

	.align 2
Cry_Audino::
	.incbin "sound/direct_sound_samples/cries/audino.bin"

	.align 2
Cry_Weavile::
	.incbin "sound/direct_sound_samples/cries/weavile.bin"

	.align 2
Cry_Steelix::
	.incbin "sound/direct_sound_samples/cries/steelix.bin"

	.align 2
Cry_Popplio::
	.incbin "sound/direct_sound_samples/cries/popplio.bin"

	.align 2
Cry_Brionne::
	.incbin "sound/direct_sound_samples/cries/brionne.bin"

	.align 2
Cry_Primarina::
	.incbin "sound/direct_sound_samples/cries/primarina.bin"

	.align 2
Cry_Scizor::
	.incbin "sound/direct_sound_samples/cries/scizor.bin"

	.align 2
Cry_Medireign::
	.incbin "sound/direct_sound_samples/cries/medireign.bin"

	.align 2
Cry_Heracross::
	.incbin "sound/direct_sound_samples/cries/heracross.bin"

	.align 2
Cry_Sneasel::
	.incbin "sound/direct_sound_samples/cries/sneasel.bin"

	.align 2
Cry_Teddiursa::
	.incbin "sound/direct_sound_samples/cries/teddiursa.bin"

	.align 2
Cry_Ursaring::
	.incbin "sound/direct_sound_samples/cries/ursaring.bin"

	.align 2
Cry_Bronzor::
	.incbin "sound/direct_sound_samples/cries/bronzor.bin"

	.align 2
Cry_Bronzong::
	.incbin "sound/direct_sound_samples/cries/bronzong.bin"

	.align 2
Cry_Swinub::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Piloswine::
	.incbin "sound/direct_sound_samples/cries/piloswine.bin"

	.align 2
Cry_Mamoswine::
	.incbin "sound/direct_sound_samples/cries/mamoswine.bin"

	.align 2
Cry_Zekrom::
	.incbin "sound/direct_sound_samples/cries/zekrom.bin"

	.align 2
Cry_Shinx::
	.incbin "sound/direct_sound_samples/cries/shinx.bin"

	.align 2
Cry_Luxio::
	.incbin "sound/direct_sound_samples/cries/luxio.bin"

	.align 2
Cry_Luxray::
	.incbin "sound/direct_sound_samples/cries/luxray.bin"

	.align 2
Cry_Skarmory::
	.incbin "sound/direct_sound_samples/cries/skarmory.bin"

	.align 2
Cry_Houndour::
	.incbin "sound/direct_sound_samples/cries/houndour.bin"

	.align 2
Cry_Houndoom::
	.incbin "sound/direct_sound_samples/cries/houndoom.bin"

	.align 2
Cry_Houndread::
	.incbin "sound/direct_sound_samples/cries/houndread.bin"

	.align 2
Cry_Litleo::
	.incbin "sound/direct_sound_samples/cries/litleo.bin"

	.align 2
Cry_Pyroar::
	.incbin "sound/direct_sound_samples/cries/pyroar.bin"

	.align 2
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cries/porygon2.bin"

	.align 2
Cry_Reshiram::
	.incbin "sound/direct_sound_samples/cries/reshiram.bin"

	.align 2
Cry_Smeargle::
	.incbin "sound/direct_sound_samples/cries/smeargle.bin"

	.align 2
Cry_Tyrogue::
	.incbin "sound/direct_sound_samples/cries/tyrogue.bin"

	.align 2
Cry_Hitmontop::
	.incbin "sound/direct_sound_samples/cries/hitmontop.bin"

	.align 2
Cry_Gothita::
	.incbin "sound/direct_sound_samples/cries/gothita.bin"

	.align 2
Cry_Gothorita::
	.incbin "sound/direct_sound_samples/cries/gothorita.bin"

	.align 2
Cry_Gothitelle::
	.incbin "sound/direct_sound_samples/cries/gothitelle.bin"

	.align 2
Cry_Bonded_Mewtwo_Y::
	.incbin "sound/direct_sound_samples/cries/bonded_mewtwo_y.bin"

	.align 2
Cry_Blissey::
	.incbin "sound/direct_sound_samples/cries/blissey.bin"

	.align 2
Cry_Rotom_Fan::
	.incbin "sound/direct_sound_samples/cries/raikou.bin"

	.align 2
Cry_Rotom_Mow::
	.incbin "sound/direct_sound_samples/cries/entei.bin"

	.align 2
Cry_Rotom_Heat::
	.incbin "sound/direct_sound_samples/cries/suicune.bin"

	.align 2
Cry_Larvitar::
	.incbin "sound/direct_sound_samples/cries/larvitar.bin"

	.align 2
Cry_Pupitar::
	.incbin "sound/direct_sound_samples/cries/pupitar.bin"

	.align 2
Cry_Tyranitar::
	.incbin "sound/direct_sound_samples/cries/tyranitar.bin"

	.align 2
Cry_Rotom_Wash::
	.incbin "sound/direct_sound_samples/cries/lugia.bin"

	.align 2
Cry_Rotom_Freeze::
	.incbin "sound/direct_sound_samples/cries/ho_oh.bin"

	.align 2
Cry_Celebi::
	.incbin "sound/direct_sound_samples/cries/celebi.bin"

	.align 2
Cry_Roggenrola::
	.incbin "sound/direct_sound_samples/cries/roggenrola.bin"

	.align 2
Cry_Giratina::
	.incbin "sound/direct_sound_samples/cries/giratina.bin"

	.align 2
Cry_SandslashA::
	.incbin "sound/direct_sound_samples/cries/alolan_sandslash.bin"

	.align 2
Cry_Electrike::
	.incbin "sound/direct_sound_samples/cries/electrike.bin"

	.align 2
Cry_Manectric::
	.incbin "sound/direct_sound_samples/cries/manectric.bin"

	.align 2
Cry_Gurdurr::
	.incbin "sound/direct_sound_samples/cries/gurdurr.bin"

	.align 2
Cry_Kyurem_White::
	.incbin "sound/direct_sound_samples/cries/kyurem.bin"

	.align 2
Cry_Timburr::
	.incbin "sound/direct_sound_samples/cries/timburr.bin"

	.align 2
Cry_Bansheette::
	.incbin "sound/direct_sound_samples/cries/bansheette.bin"

	.align 2
Cry_Sharpedo::
	.incbin "sound/direct_sound_samples/cries/sharpedo.bin"

	.align 2
Cry_Absolom::
	.incbin "sound/direct_sound_samples/cries/absolom.bin"

	.align 2
Cry_Carracosta::
	.incbin "sound/direct_sound_samples/cries/carracosta.bin"

	.align 2
Cry_Swablu::
	.incbin "sound/direct_sound_samples/cries/swablu.bin"

	.align 2
Cry_Altaria::
	.incbin "sound/direct_sound_samples/cries/altaria.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cries/unused_265.bin"

	.align 2
Cry_Shelmet::
	.incbin "sound/direct_sound_samples/cries/shelmet.bin"

	.align 2
Cry_Accelgor::
	.incbin "sound/direct_sound_samples/cries/accelgor.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cries/unused_268.bin"

	.align 2
Cry_Palkia::
	.incbin "sound/direct_sound_samples/cries/palkia.bin"

	.align 2
Cry_Torchic::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Combusken::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Blaziken::
	.incbin "sound/direct_sound_samples/cries/blaziken.bin"

	.align 2
Cry_Treecko::
	.incbin "sound/direct_sound_samples/cries/treecko.bin"

	.align 2
Cry_Grovyle::
	.incbin "sound/direct_sound_samples/cries/grovyle.bin"

	.align 2
Cry_Sceptile::
	.incbin "sound/direct_sound_samples/cries/sceptile.bin"

	.align 2
Cry_Mudkip::
	.incbin "sound/direct_sound_samples/cries/mudkip.bin"

	.align 2
Cry_Marshtomp::
	.incbin "sound/direct_sound_samples/cries/marshtomp.bin"

	.align 2
Cry_Swampert::
	.incbin "sound/direct_sound_samples/cries/swampert.bin"

	.align 2
Cry_Pelipper::
	.incbin "sound/direct_sound_samples/cries/pelipper.bin"

	.align 2
Cry_Wingull::
	.incbin "sound/direct_sound_samples/cries/wingull.bin"

	.align 2
Cry_Banette::
	.incbin "sound/direct_sound_samples/cries/banette.bin"

	.align 2
Cry_Shuppet::
	.incbin "sound/direct_sound_samples/cries/shuppet.bin"

	.align 2
Cry_Duosion::
	.incbin "sound/direct_sound_samples/cries/duosion.bin"

	.align 2
Cry_Reuniclus::
	.incbin "sound/direct_sound_samples/cries/reuniclus.bin"

	.align 2
Cry_Pancham::
	.incbin "sound/direct_sound_samples/cries/pancham.bin"

	.align 2
Cry_Pangoro::
	.incbin "sound/direct_sound_samples/cries/pangoro.bin"

	.align 2
Cry_Mienfoo::
	.incbin "sound/direct_sound_samples/cries/mienfoo.bin"

	.align 2
Cry_Mienshao::
	.incbin "sound/direct_sound_samples/cries/mienshao.bin"

	.align 2
Cry_Carvanha::
	.incbin "sound/direct_sound_samples/cries/carvanha.bin"

	.align 2
Cry_Petilil::
	.incbin "sound/direct_sound_samples/cries/petilil.bin"

	.align 2
Cry_Lilligant::
	.incbin "sound/direct_sound_samples/cries/lilligant.bin"

	.align 2
Cry_Cottonee::
	.incbin "sound/direct_sound_samples/cries/cottonee.bin"

	.align 2
Cry_Whimsicott::
	.incbin "sound/direct_sound_samples/cries/whimsicott.bin"

	.align 2
Cry_Solosis::
	.incbin "sound/direct_sound_samples/cries/solosis.bin"

	.align 2
Cry_Ralts::
	.incbin "sound/direct_sound_samples/cries/ralts.bin"

	.align 2
Cry_Kirlia::
	.incbin "sound/direct_sound_samples/cries/kirlia.bin"

	.align 2
Cry_Gardevoir::
	.incbin "sound/direct_sound_samples/cries/gardevoir.bin"

	.align 2
Cry_Fletchling::
	.incbin "sound/direct_sound_samples/cries/fletchling.bin"

	.align 2
Cry_Fletchindr::
	.incbin "sound/direct_sound_samples/cries/fletchindr.bin"

	.align 2
Cry_Talonflame::
	.incbin "sound/direct_sound_samples/cries/talonflame.bin"

	.align 2
Cry_Amaura::
	.incbin "sound/direct_sound_samples/cries/amaura.bin"

	.align 2
Cry_Aurorus::
	.incbin "sound/direct_sound_samples/cries/aurorus.bin"

	.align 2
Cry_Dialga::
	.incbin "sound/direct_sound_samples/cries/dialga.bin"

	.align 2
Cry_Dwebble::
	.incbin "sound/direct_sound_samples/cries/dwebble.bin"

	.align 2
Cry_Crustle::
	.incbin "sound/direct_sound_samples/cries/crustle.bin"

	.align 2
Cry_SandshrewA::
	.incbin "sound/direct_sound_samples/cries/alolan_sandshrew.bin"

	.align 2
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cries/glalie.bin"

	.align 2
Cry_Salandit::
	.incbin "sound/direct_sound_samples/cries/salandit.bin"

	.align 2
Cry_Salazzle::
	.incbin "sound/direct_sound_samples/cries/salazzle.bin"

	.align 2
Cry_Riolu::
	.incbin "sound/direct_sound_samples/cries/riolu.bin"

	.align 2
Cry_Lucario::
	.incbin "sound/direct_sound_samples/cries/lucario.bin"

	.align 2
Cry_Skitty::
	.incbin "sound/direct_sound_samples/cries/skitty.bin"

	.align 2
Cry_Delcatty::
	.incbin "sound/direct_sound_samples/cries/delcatty.bin"

	.align 2
Cry_Giratina_Origin::
	.incbin "sound/direct_sound_samples/cries/giratina_origin.bin"

	.align 2
Cry_Bonded_Serperior::
	.incbin "sound/direct_sound_samples/cries/bonded_serperior.bin"

	.align 2
Cry_Manethundr::
	.incbin "sound/direct_sound_samples/cries/manethundr.bin"

	.align 2
Cry_PorygonZ::
	.incbin "sound/direct_sound_samples/cries/porygonZ.bin"

	.align 2
Cry_Litwick::
	.incbin "sound/direct_sound_samples/cries/litwick.bin"

	.align 2
Cry_Lampent::
	.incbin "sound/direct_sound_samples/cries/lampent.bin"

	.align 2
Cry_Corphish::
	.incbin "sound/direct_sound_samples/cries/corphish.bin"

	.align 2
Cry_Crawdaunt::
	.incbin "sound/direct_sound_samples/cries/crawdaunt.bin"

	.align 2
Cry_Spoink::
	.incbin "sound/direct_sound_samples/cries/spoink.bin"

	.align 2
Cry_Grumpig::
	.incbin "sound/direct_sound_samples/cries/grumpig.bin"

	.align 2
Cry_Trapinch::
	.incbin "sound/direct_sound_samples/cries/trapinch.bin"

	.align 2
Cry_Vibrava::
	.incbin "sound/direct_sound_samples/cries/vibrava.bin"

	.align 2
Cry_Flygon::
	.incbin "sound/direct_sound_samples/cries/flygon.bin"

	.align 2
Cry_Cacnea::
	.incbin "sound/direct_sound_samples/cries/cacnea.bin"

	.align 2
Cry_Cacturne::
	.incbin "sound/direct_sound_samples/cries/cacturne.bin"

	.align 2
Cry_Boldore::
	.incbin "sound/direct_sound_samples/cries/boldore.bin"

	.align 2
Cry_Gigalith::
	.incbin "sound/direct_sound_samples/cries/gigalith.bin"

	.align 2
Cry_Froslass::
	.incbin "sound/direct_sound_samples/cries/froslass.bin"

	.align 2
Cry_Tirtouga::
	.incbin "sound/direct_sound_samples/cries/tirtouga.bin"

	.align 2
Cry_Feebas::
	.incbin "sound/direct_sound_samples/cries/feebas.bin"

	.align 2
Cry_Milotic::
	.incbin "sound/direct_sound_samples/cries/milotic.bin"

	.align 2
Cry_Absol::
	.incbin "sound/direct_sound_samples/cries/absol.bin"

	.align 2
Cry_Meditite::
	.incbin "sound/direct_sound_samples/cries/meditite.bin"

	.align 2
Cry_Medicham::
	.incbin "sound/direct_sound_samples/cries/medicham.bin"

	.align 2
Cry_Tynamo::
	.incbin "sound/direct_sound_samples/cries/tynamo.bin"

	.align 2
Cry_Eelektrik::
	.incbin "sound/direct_sound_samples/cries/eelektrik.bin"

	.align 2
Cry_Eelektross::
	.incbin "sound/direct_sound_samples/cries/eelektross.bin"

	.align 2
Cry_Azelf::
	.incbin "sound/direct_sound_samples/cries/azelf.bin"

	.align 2
Cry_Mesprit::
	.incbin "sound/direct_sound_samples/cries/mesprit.bin"

	.align 2
Cry_Uxie::
	.incbin "sound/direct_sound_samples/cries/uxie.bin"

	.align 2
Cry_Lileep::
	.incbin "sound/direct_sound_samples/cries/lileep.bin"

	.align 2
Cry_Cradily::
	.incbin "sound/direct_sound_samples/cries/cradily.bin"

	.align 2
Cry_Anorith::
	.incbin "sound/direct_sound_samples/cries/anorith.bin"

	.align 2
Cry_Armaldo::
	.incbin "sound/direct_sound_samples/cries/armaldo.bin"

	.align 2
Cry_Beldum::
	.incbin "sound/direct_sound_samples/cries/beldum.bin"

	.align 2
Cry_Metang::
	.incbin "sound/direct_sound_samples/cries/metang.bin"

	.align 2
Cry_Metagross::
	.incbin "sound/direct_sound_samples/cries/metagross.bin"

	.align 2
Cry_Bagon::
	.incbin "sound/direct_sound_samples/cries/bagon.bin"

	.align 2
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cries/shelgon.bin"

	.align 2
Cry_Rockruff::
	.incbin "sound/direct_sound_samples/cries/rockruff.bin"

	.align 2
Cry_Lycanroc::
	.incbin "sound/direct_sound_samples/cries/lycanroc.bin"

	.align 2
Cry_Bonded_Aerodactyl::
	.incbin "sound/direct_sound_samples/cries/bonded_aerodactyl.bin"

	.align 2
Cry_MarowakA::
	.incbin "sound/direct_sound_samples/cries/marowak.bin"

	.align 2
Cry_Rhyperior::
	.incbin "sound/direct_sound_samples/cries/rhyperior.bin"

	.align 2
Cry_Gallade::
	.incbin "sound/direct_sound_samples/cries/gallade.bin"

	.align 2
Cry_Poochyena::
	.incbin "sound/direct_sound_samples/cries/poochyena.bin"

	.align 2
Cry_Mightyena::
	.incbin "sound/direct_sound_samples/cries/mightyena.bin"

	.align 2
Cry_Conkeldurr::
	.incbin "sound/direct_sound_samples/cries/conkeldurr.bin"

	.align 2
Cry_Sableye::
	.incbin "sound/direct_sound_samples/cries/sableye.bin"

	.align 2
Cry_Mawile::
	.incbin "sound/direct_sound_samples/cries/mawile.bin"

	.align 2
Cry_Aron::
	.incbin "sound/direct_sound_samples/cries/aron.bin"

	.align 2
Cry_Lairon::
	.incbin "sound/direct_sound_samples/cries/lairon.bin"

	.align 2
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cries/aggron.bin"

	.align 2
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Chandelure::
	.incbin "sound/direct_sound_samples/cries/chandelure.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cries/groudon.bin"

	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cries/kyogre.bin"

	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/rayquaza.bin"

	.align 2
Cry_Salamence::
	.incbin "sound/direct_sound_samples/cries/salamence.bin"

	.align 2
Cry_Breloom::
	.incbin "sound/direct_sound_samples/cries/breloom.bin"

	.align 2
Cry_Shroomish::
	.incbin "sound/direct_sound_samples/cries/shroomish.bin"

	.align 2
Cry_Linoone::
	.incbin "sound/direct_sound_samples/cries/linoone.bin"

	.align 2
Cry_Kyurem::
	.incbin "sound/direct_sound_samples/cries/kyurem.bin"

	.align 2
Cry_Wailmer::
	.incbin "sound/direct_sound_samples/cries/wailmer.bin"

	.align 2
Cry_Zigzagoon::
	.incbin "sound/direct_sound_samples/cries/zigzagoon.bin"

	.align 2
Cry_Lopunny::
	.incbin "sound/direct_sound_samples/cries/lopunny.bin"

	.align 2
Cry_Buneary::
	.incbin "sound/direct_sound_samples/cries/buneary.bin"

	.align 2
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cries/wailord.bin"

	.align 2
Cry_Meloetta::
	.incbin "sound/direct_sound_samples/cries/meloetta.bin"

	.align 2
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cries/snorunt.bin"

	.align 2
Cry_Kyurem_Black::
	.incbin "sound/direct_sound_samples/cries/kyurem.bin"

	.align 2
Cry_Bonded_Aggron::
	.incbin "sound/direct_sound_samples/cries/bonded_aggron.bin"

	.align 2
Cry_Bonded_Alakazam::
	.incbin "sound/direct_sound_samples/cries/bonded_alakazam.bin"

	.align 2
Cry_Arceus::
	.incbin "sound/direct_sound_samples/cries/arceus.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_sc88_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
